[package]
name = "deps"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
anyhow = "1.0"
rand = "0.8"
ron = "0.7"
serde = {version = "1", features = ["derive"]}
# bytemuck = { path = "../../../bytemuck", features  = ["derive", "proc-macro-crate"] }

# TODO: ansi parser
tracing = "0.1"
tracing-subscriber = "0.3.9" # TODO: enable parling lot
tracing-appender = "0.2.0"
tracing-unwrap = "0.9"
tracing-log = "0.1"

#tracing-log = { version = "0.1", features = ["env_logger"] }
futures-lite = "1.11"
smartstring = "1.0"
downcast-rs = "1.2"
parking_lot = { version = "0.12.0", features = ["nightly"] }
# TODO: smallset
smallvec = "1.6"
chrono = "0.4"
splines = { version = "4.0.3", features = ["serde", "glam", "nalgebra"] }
bitflags = "1.2"
once_cell = "1.8"
# derivative = { version = "2.2.0", }

bevy = { version = "0.6.1", features = ["jpeg"] } 
bevy_egui = "0.11"
# bevy_rapier3d = { version = "0.12", features = [ "parallel", "render", "simd-nightly"]}
bevy_rapier3d = { version = "0.12", features = ["render"]}
bevy_prototype_debug_lines = { git = "https://github.com/Toqozz/bevy_debug_lines", rev = "69bf4dd", features = ["3d"] }
bevy-inspector-egui = { version = "0.8.2", features =  [] }
educe = "0.4.18"
bevy_polyline = "0.1.1"
big-brain = "0.10.0"
# bevy_mod_debugdump = "0.2.1"
# bevy_config_cam = "0.1.2"
bevy_mod_picking = "0.5.2"
bevy_mod_raycast = "0.3.9"


