[package]
name = "deps"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
# eyre = "0.6"
color-eyre = "0.6.0"
rand = "0.8"
ron = "0.7"
serde = { version = "1", features = ["derive"] }
educe = "0.4.18"
# bytemuck = { path = "../../../bytemuck", features  = ["derive", "proc-macro-crate"] }

# TODO: ansi parser
tracing = "0.1"
tracing-subscriber = {version = "0.3.9", features = ["env-filter", "parking_lot"]}
tracing-appender = "0.2.2"
tracing-unwrap = "0.9"
tracing-error = "0.2"


#tracing-log = { version = "0.1", features = ["env_logger"] }
futures-lite = "1.11"
smartstring = "1.0"
downcast-rs = "1.2"
parking_lot = { version = "*", features = ["nightly"] }
smallvec = "1.6"
chrono = "0.4"
# splines = { version = "4.0.3", features = ["glam", "nalgebra"] }
bitflags = "1.2"
once_cell = "1.8"
# derivative = { version = "2.2.0", }

bevy = { version = "0.8", features = ["jpeg", "wayland"] } 
bevy_egui = "0.15.0"
bevy_rapier3d = { version = "0.16.0" }
bevy_prototype_debug_lines = { version = "0.8", features = ["3d"] }
bevy-inspector-egui = { version = "0.12.1", features = [] }
# bevy_polyline = "0.2.0"
big-brain = "0.12.0"
# bevy_mod_debugdump = "0.2.1"
# bevy_config_cam = "0.1.2"
bevy_mod_picking = "0.8.0"
bevy_mod_raycast = "0.6.0"
# bevy_plot = "0.1"

[build-dependencies]
cargo_toml = "0.11"
toml = "*"
