[package]
name = "deps"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
anyhow = "1.0"
rand = "0.8"
ron = "0.6"
serde = {version = "1", features = ["derive"]}
# bytemuck = { path = "../../../bytemuck", features  = ["derive", "proc-macro-crate"] }
tracing = "0.1"
tracing-subscriber = "0.2.0"
#tracing-log = { version = "0.1", features = ["env_logger"] }
futures-lite = "1.11"
smartstring = "0.2"
downcast-rs = "1.2"
parking_lot = { version = "0.11", features = ["nightly"] }
smallvec = "1.6"
chrono = "0.4"
splines = { version = "4.0.3", features = ["serde", "glam", "nalgebra"] }
bitflags = "1.2"
once_cell = "1.8"
# derivative = { version = "2.2.0", }

bevy = "0.5" 
bevy_egui = "0.6"
bevy_rapier3d = { version = "0.10", features = ["simd-nightly", "parallel", "render"]}
bevy_prototype_debug_lines = "0.3.2"
bevy-inspector-egui = { version = "0.6.1", features =  ["rapier"] }
bevy_mod_debugdump = "0.2.1"
# bevy_config_cam = "0.1.2"


